repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-added-large-files
        args: ["--maxkb=50000"]
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args: ["--namespace-packages", "--config-file", "pyproject.toml"]
        additional_dependencies:
          - pydantic
          - pydantic-settings
          - types-PyYAML

  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1
    hooks:
      - id: hadolint
        name: Lint Dockerfiles
        entry: hadolint
        language: system
        types: [file]
        files: ^Dockerfile

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args:
          - --config-data
          - >
            {extends: default,
             rules: {line-length: disable}}

  - repo: https://github.com/pycqa/bandit
    rev: "1.8.6"
    hooks:
      - id: bandit
        args: ["-q"]
        files: ^src/.*\.py$

  - repo: https://github.com/kynan/nbstripout
    rev: "0.8.1"
    hooks:
      - id: nbstripout

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args:
          - --write-changes
          - --check-hidden
          - --ignore-words=./.codespell.ignorewords
